packages:
  - packages/*
  - fixtures/*
  - fixtures/monorepo/packages/*
minimumReleaseAgeExclude:
  - '@vitest/mocker@5.0.2'
  - '@vitest/spy@5.0.2'
  - vitest@5.0.2
allowBuilds:
  esbuild: true
  '@parcel/watcher': false
  unrs-resolver: false
