#!/usr/bin/env node
/**
 * tzap's benchmark harness (M7): scenarios from docs/parity-and-benchmarks.md §5, tzap against
 * StrykerJS on the same generated fixture, same machine, same Node, same Vitest.
 *
 *   node tools/bench/bench.mjs [--runs 5] [--stryker-runs 3] [--only S1,S3,...] [--no-stryker]
 *                              [--no-reference] [--no-scaling] [--stryker-concurrency N]
 *                              [--work DIR] [--out tools/bench/results/raw-<platform>.json]
 *   node tools/bench/render.mjs  (turns the raw JSON into report.md and the checked-in text)
 *
 * Method (jzap's lessons, docs/parity-and-benchmarks.md §5):
 * - Median of N with min–max, never a best run. tzap 5 runs, Stryker 3 (it is slow).
 * - tzap and Stryker runs are interleaved, so slow drift in background load hits both.
 * - Work parity next to every time: inventory per tool, the mapped intersection, verdict counts.
 * - S3's patch is derived from the inventory; no figure is recorded when it hits no mutant.
 * - Background CPU load is sampled before every scenario and recorded with it.
 *
 * Where it runs: the fixture (fixtures/bench-vitest, generated by generate.mjs) is copied to a
 * work directory OUTSIDE the repository (default: <os tmp>/tzap-bench), because tzap's discovery
 * walks up to the nearest pnpm-workspace.yaml, and installed there with Vitest 4.1.x: Stryker's
 * Vitest runner 10.0.0 does not work with Vitest 5 (stryker-js#6210), and both tools must run on
 * the same Vitest. tzap itself is the workspace build (packages/tzap/dist/bin.js).
 */
import { spawn, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync, readdirSync, realpathSync, symlinkSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, '../..');
let TZAP = path.join(REPO, 'packages', 'tzap', 'dist', 'bin.js'); // replaced by the snapshot below
const FIXTURE = path.join(REPO, 'fixtures', 'bench-vitest');

// ---------------------------------------------------------------------------------------------
// Arguments

const argv = process.argv.slice(2);
const flag = (name) => argv.includes(`--${name}`);
const opt = (name, dflt) => (argv.includes(`--${name}`) ? argv[argv.indexOf(`--${name}`) + 1] : dflt);
const RUNS = Number(opt('runs', 5));
const STRYKER_RUNS = Number(opt('stryker-runs', 3));
const ONLY = opt('only', 'S1,S3,S4,S5,S6,S9').split(',');
const WITH_STRYKER = !flag('no-stryker');
const WITH_REFERENCE = !flag('no-reference');
const WITH_SCALING = !flag('no-scaling');
const PLATFORM = process.platform === 'win32' ? 'windows' : process.platform;
const WORK = path.resolve(opt('work', path.join(os.tmpdir(), 'tzap-bench')));
const OUT = path.resolve(opt('out', path.join(HERE, 'results', `raw-${PLATFORM}.json`)));
const SCALING = [1, 2, 4, 8];
const STRYKER_CANDIDATES = [1, 4, Math.max(1, Math.floor(os.availableParallelism() / 2))];

const log = (...a) => process.stderr.write(`${a.join(' ')}\n`);

// The child environment: a plain developer terminal. Vitest 4.1 switches reporters when it detects
// an AI agent (std-env isAgent), which would make the harness measure something no user runs.
const CHILD_ENV = Object.fromEntries(
  Object.entries(process.env).filter(([k]) => !/^(AI_AGENT|CLAUDECODE|CLAUDE_CODE_.*|CODEX_.*|CURSOR_AGENT|GEMINI_CLI|AGENT)$/.test(k)),
);
CHILD_ENV.NO_COLOR = '1';
CHILD_ENV.FORCE_COLOR = '0';


// ---------------------------------------------------------------------------------------------
// A frozen copy of the tzap build. The workspace is shared: other work rebuilds packages/*/dist
// while a bench runs, and the first full run of this harness mixed two builds inside one scenario
// (phase shapes changed between run 3 and run 4 of S1). Every tzap run therefore uses a snapshot
// taken once, verified to be one consistent build, and identified by its hash in the report.

function listFiles(dir, rel = '') {
  const out = [];
  if (!existsSync(path.join(dir, rel))) return out;
  for (const e of readdirSync(path.join(dir, rel), { withFileTypes: true })) {
    const r = path.join(rel, e.name);
    if (e.isDirectory()) out.push(...listFiles(dir, r));
    else if (/\.(js|mjs|cjs|json)$/.test(e.name) && !e.name.endsWith('.map')) out.push(r);
  }
  return out.sort();
}
function buildHash(pkgDirs) {
  const h = createHash('sha256');
  for (const [name, dist] of pkgDirs) for (const f of listFiles(dist)) h.update(`${name}/${f.split(path.sep).join('/')}|`).update(readFileSync(path.join(dist, f)));
  return h.digest('hex').slice(0, 16);
}
async function snapshotTzap() {
  const pkgs = readdirSync(path.join(REPO, 'packages')).filter((d) => existsSync(path.join(REPO, 'packages', d, 'package.json')));
  const meta = pkgs.map((d) => ({ dir: path.join(REPO, 'packages', d), name: JSON.parse(readFileSync(path.join(REPO, 'packages', d, 'package.json'), 'utf8')).name }));
  const snap = path.join(WORK, 'tzap-build');
  const nm = path.join(snap, 'node_modules');
  for (let attempt = 1; attempt <= 20; attempt++) {
    const before = buildHash(meta.map((m) => [m.name, path.join(m.dir, 'dist')]));
    rmSync(snap, { recursive: true, force: true });
    mkdirSync(nm, { recursive: true });
    for (const m of meta) {
      const to = path.join(nm, ...m.name.split('/'));
      mkdirSync(to, { recursive: true });
      cpSync(path.join(m.dir, 'package.json'), path.join(to, 'package.json'));
      if (existsSync(path.join(m.dir, 'dist'))) cpSync(path.join(m.dir, 'dist'), path.join(to, 'dist'), { recursive: true });
    }
    // Third-party dependencies are linked, not copied: they change only with the lockfile.
    for (const m of meta) {
      const own = path.join(m.dir, 'node_modules');
      if (!existsSync(own)) continue;
      const pj = JSON.parse(readFileSync(path.join(m.dir, 'package.json'), 'utf8'));
      const entries = Object.keys({ ...pj.dependencies, ...pj.optionalDependencies, ...pj.peerDependencies });
      for (const dep of entries) {
        if (dep.startsWith('@tzap/') || !existsSync(path.join(own, ...dep.split('/')))) continue;
        const dest = path.join(nm, ...dep.split('/'));
        if (existsSync(dest)) continue;
        mkdirSync(path.dirname(dest), { recursive: true });
        symlinkSync(realpathSync(path.join(own, ...dep.split('/'))), dest, 'junction');
      }
    }
    const after = buildHash(meta.map((m) => [m.name, path.join(m.dir, 'dist')]));
    const copied = buildHash(meta.map((m) => [m.name, path.join(nm, ...m.name.split('/'), 'dist')]));
    if (before === after && after === copied) return { bin: path.join(nm, 'tzap', 'dist', 'bin.js'), hash: copied, attempts: attempt };
    log(`tzap build changed while it was being copied (attempt ${attempt}); retrying in 10 s`);
    await new Promise((r) => setTimeout(r, 10_000));
  }
  throw new Error('the tzap build kept changing for 20 attempts; run the bench when nothing is rebuilding packages/*/dist');
}

// ---------------------------------------------------------------------------------------------
// Machine and load

function cpuTimes() {
  return os.cpus().map((c) => c.times);
}
async function cpuBusy(ms = 2000) {
  const a = cpuTimes();
  await new Promise((r) => setTimeout(r, ms));
  const b = cpuTimes();
  let busy = 0, total = 0;
  for (let i = 0; i < a.length; i++) {
    const d = (k) => b[i][k] - a[i][k];
    const t = d('user') + d('nice') + d('sys') + d('idle') + d('irq');
    total += t;
    busy += t - d('idle');
  }
  return Math.round((1000 * busy) / total) / 10;
}

function machine() {
  const cpus = os.cpus();
  const git = spawnSync('git', ['rev-parse', '--short', 'HEAD'], { cwd: REPO, encoding: 'utf8' }).stdout.trim();
  const dirty = spawnSync('git', ['status', '--porcelain', '--', 'packages'], { cwd: REPO, encoding: 'utf8' }).stdout.trim() !== '';
  return {
    platform: `${os.type()} ${os.release()} (${process.platform})`,
    cpu: cpus[0]?.model.trim(),
    logicalCpus: os.availableParallelism(),
    memoryGB: Math.round(os.totalmem() / 2 ** 30),
    node: process.version,
    tzapCommit: `${git}${dirty ? '+dirty' : ''}`,
    tzapVersion: spawnSync(process.execPath, [TZAP, '--version'], { encoding: 'utf8' }).stdout.trim(),
    date: new Date().toISOString(),
  };
}

// ---------------------------------------------------------------------------------------------
// Work directory: a runnable copy of each fixture variant, installed once

const PINS = JSON.parse(readFileSync(path.join(HERE, 'config', 'package.pins.json'), 'utf8'));

function setupVariant(variant) {
  const dir = path.join(WORK, variant);
  const pkg = { name: `tzap-bench-${variant}`, private: true, type: 'module', scripts: { test: 'vitest run' }, devDependencies: PINS };
  const pkgText = `${JSON.stringify(pkg, null, 2)}\n`;
  mkdirSync(dir, { recursive: true });
  let install;
  if (!existsSync(path.join(dir, 'node_modules', 'vitest')) || !existsSync(path.join(dir, 'package.json')) || readFileSync(path.join(dir, 'package.json'), 'utf8') !== pkgText) {
    writeFileSync(path.join(dir, 'package.json'), pkgText);
    log(`install ${variant}: npm install ${Object.entries(PINS).map(([k, v]) => `${k}@${v}`).join(' ')}`);
    const t = performance.now();
    const r = spawnSync('npm install --no-audit --no-fund', { cwd: dir, encoding: 'utf8', shell: true, env: CHILD_ENV });
    if (r.status !== 0) throw new Error(`npm install failed in ${dir}:\n${r.stderr}`);
    install = Math.round(performance.now() - t);
  }
  resetSources(variant);
  cpSync(path.join(HERE, 'config', 'vitest.config.ts'), path.join(dir, 'vitest.config.ts'));
  cpSync(path.join(HERE, 'config', 'stryker.config.json'), path.join(dir, 'stryker.config.json'));
  const vitestVersion = JSON.parse(readFileSync(path.join(dir, 'node_modules', 'vitest', 'package.json'), 'utf8')).version;
  const strykerVersion = JSON.parse(readFileSync(path.join(dir, 'node_modules', '@stryker-mutator', 'core', 'package.json'), 'utf8')).version;
  return { dir, installMs: install, vitestVersion, strykerVersion };
}

function resetSources(variant) {
  const dir = path.join(WORK, variant);
  for (const sub of ['src', 'test', 'reports', '.stryker-tmp']) rmSync(path.join(dir, sub), { recursive: true, force: true });
  cpSync(path.join(FIXTURE, variant, 'src'), path.join(dir, 'src'), { recursive: true });
  cpSync(path.join(FIXTURE, variant, 'test'), path.join(dir, 'test'), { recursive: true });
}

// ---------------------------------------------------------------------------------------------
// Running the tools

/** Spawns a command, timestamping every output line on arrival (for phase attribution). */
function exec(cmd, args, cwd) {
  return new Promise((resolve) => {
    const t0 = performance.now();
    const child = spawn(cmd, args, { cwd, env: CHILD_ENV });
    const lines = [];
    let buf = { out: '', err: '' };
    const take = (k) => (chunk) => {
      buf[k] += chunk.toString();
      let i;
      while ((i = buf[k].indexOf('\n')) >= 0) {
        lines.push({ t: performance.now() - t0, k, s: buf[k].slice(0, i).replace(/\x1b\[[0-9;]*m/g, '') });
        buf[k] = buf[k].slice(i + 1);
      }
    };
    child.stdout.on('data', take('out'));
    child.stderr.on('data', take('err'));
    child.on('close', (code) => resolve({ code, ms: performance.now() - t0, lines }));
  });
}

const count = (ms, f = (m) => m.status) => ms.reduce((c, m) => ((c[f(m)] = (c[f(m)] ?? 0) + 1), c), {});

async function tzap(dir, args, { reportDir }) {
  rmSync(reportDir, { recursive: true, force: true });
  const r = await exec(process.execPath, [TZAP, 'run', '-r', 'json', '-o', reportDir, '--no-arid', '-q', ...args], dir);
  if (r.code !== 0 && r.code !== 1) throw new Error(`tzap exited ${r.code} in ${dir} (${args.join(' ')}):\n${r.lines.slice(-20).map((l) => l.s).join('\n')}`);
  const rep = JSON.parse(readFileSync(path.join(reportDir, 'tzap.json'), 'utf8'));
  const ms = rep.mutants;
  const executed = ms.filter((m) => !m.cached && (m.testsCompleted ?? 0) > 0);
  const testsRun = executed.reduce((a, m) => a + (m.testsCompleted ?? 0), 0);
  return {
    ms: Math.round(r.ms),
    phases: rep.timings,
    inventory: ms.length,
    executed: executed.length,
    cached: ms.filter((m) => m.cached).length,
    static: ms.filter((m) => m.static).length,
    testExecutions: testsRun,
    verdicts: count(ms),
    redTests: rep.redTests?.length ?? 0,
    mutants: ms,
  };
}

function strykerMutants(report) {
  const out = [];
  for (const [file, f] of Object.entries(report.files)) for (const m of f.mutants) out.push({ ...m, file });
  return out;
}

async function stryker(dir, args) {
  rmSync(path.join(dir, '.stryker-tmp'), { recursive: true, force: true });
  rmSync(path.join(dir, 'reports', 'stryker.json'), { force: true });
  const bin = path.join(dir, 'node_modules', '@stryker-mutator', 'core', 'bin', 'stryker.js');
  const r = await exec(process.execPath, [bin, 'run', ...args], dir);
  const reportFile = path.join(dir, 'reports', 'stryker.json');
  if (r.code !== 0 || !existsSync(reportFile)) throw new Error(`stryker exited ${r.code} in ${dir} (${args.join(' ')}):\n${r.lines.slice(-30).map((l) => l.s).join('\n')}`);
  const ms = strykerMutants(JSON.parse(readFileSync(reportFile, 'utf8')));
  const at = (re) => r.lines.find((l) => re.test(l.s))?.t;
  const instrumented = at(/Instrumented \d+ source file/);
  const dryStart = at(/Starting initial test run/);
  const dryEnd = at(/Initial test run succeeded/);
  const reusedLine = r.lines.find((l) => /mutant result\(s\) are reused/.test(l.s))?.s;
  const reused = reusedLine ? Number(/(\d+) of \d+ mutant result/.exec(reusedLine)[1]) : 0;
  const executed = ms.filter((m) => (m.testsCompleted ?? 0) > 0 && m.status !== 'NoCoverage');
  return {
    ms: Math.round(r.ms),
    phases: {
      startup_instrument: instrumented !== undefined ? Math.round(instrumented) : undefined,
      dryRun: dryStart !== undefined && dryEnd !== undefined ? Math.round(dryEnd - dryStart) : undefined,
      mutate: dryEnd !== undefined ? Math.round(r.ms - dryEnd) : undefined,
    },
    inventory: ms.length,
    // Reused results carry their old testsCompleted; count them out of the executed figure.
    executed: Math.max(0, executed.length - reused),
    cached: reused,
    static: ms.filter((m) => m.static).length,
    testExecutions: reused ? undefined : executed.reduce((a, m) => a + (m.testsCompleted ?? 0), 0),
    verdicts: count(ms),
    mutants: ms,
  };
}

// ---------------------------------------------------------------------------------------------
// Work parity: Stryker's incremental key, replacement normalised (both tools print parentheses and
// whitespace differently), per docs/parity-and-benchmarks.md §3.

const norm = (s) => String(s).replace(/[\s()]/g, '').replace(/"/g, "'");
const key = (m) => `${m.file.replace(/\\/g, '/').replace(/^.*?\bsrc\//, 'src/')}:${m.location.start.line}:${m.location.start.column}-${m.location.end.line}:${m.location.end.column} ${m.mutatorName} ${norm(m.replacement)}`;

function parity(a, b) {
  const A = new Map(a.map((m) => [key(m), m]));
  const B = new Map(b.map((m) => [key(m), m]));
  const shared = [...A.keys()].filter((k) => B.has(k));
  const disagree = {};
  for (const k of shared) {
    const x = A.get(k).status, y = B.get(k).status;
    if (x !== y) disagree[`${x}/${y}`] = (disagree[`${x}/${y}`] ?? 0) + 1;
  }
  const only = (X, Y) => [...X.keys()].filter((k) => !Y.has(k));
  const aOnly = only(A, B), bOnly = only(B, A);
  return { shared: shared.length, aOnly: aOnly.length, bOnly: bOnly.length, aOnlySample: aOnly.slice(0, 5), bOnlySample: bOnly.slice(0, 5), disagree };
}

const strip = ({ mutants, ...rest }) => rest;

// ---------------------------------------------------------------------------------------------
// S3: a synthetic ~10-line patch derived from the inventory

function inventory(dir, extra = []) {
  const r = spawnSync(process.execPath, [TZAP, 'list-mutants', '--format', 'json', '--no-arid', ...extra], { cwd: dir, encoding: 'utf8', env: CHILD_ENV, maxBuffer: 1 << 28 });
  if (r.status !== 0) throw new Error(`list-mutants failed: ${r.stderr}`);
  return JSON.parse(r.stdout);
}

function makePatch(dir, inv) {
  // Deterministic: two files chosen by a fixed stride over the sorted file list, and in each a
  // window of five consecutive mutant-bearing lines — about ten changed lines, like a small PR.
  const byFile = new Map();
  for (const m of inv) {
    const f = m.file.replace(/\\/g, '/');
    if (!byFile.has(f)) byFile.set(f, new Set());
    byFile.get(f).add(m.location.start.line);
  }
  const files = [...byFile.keys()].sort();
  const chosen = [files[Math.floor(files.length * 0.3)], files[Math.floor(files.length * 0.7)]];
  let diff = '';
  const ranges = [];
  let changed = 0;
  for (const f of chosen) {
    const lines = [...byFile.get(f)].sort((a, b) => a - b);
    const start = Math.floor(lines.length / 3);
    const pickLines = lines.slice(start, start + 5);
    const text = readFileSync(path.join(dir, f), 'utf8').split('\n');
    // Group consecutive lines into hunks.
    const hunks = [];
    for (const l of pickLines) {
      const h = hunks.at(-1);
      if (h && l === h[1] + 1) h[1] = l;
      else hunks.push([l, l]);
    }
    diff += `diff --git a/${f} b/${f}\n--- a/${f}\n+++ b/${f}\n`;
    for (const [a, b] of hunks) {
      const n = b - a + 1;
      diff += `@@ -${a},${n} +${a},${n} @@\n`;
      for (let l = a; l <= b; l++) diff += `-${text[l - 1]} // before\n`;
      for (let l = a; l <= b; l++) diff += `+${text[l - 1]}\n`;
      ranges.push(`${f}:${a}-${b}`);
      changed += n;
    }
  }
  return { diff, ranges, changedLines: changed, files: chosen };
}

// ---------------------------------------------------------------------------------------------
// Scenario bookkeeping

const results = { machine: {}, config: {}, scenarios: {}, notes: [] };
const save = () => {
  mkdirSync(path.dirname(OUT), { recursive: true });
  writeFileSync(OUT, `${JSON.stringify(results, null, 2)}\n`);
};

function series(label, tool, runs, extra = {}) {
  return { label, tool, runs: runs.map(strip), ...extra };
}

async function timed(label, n, fn) {
  const out = [];
  for (let i = 0; i < n; i++) {
    const r = await fn(i);
    out.push(r);
    log(`  ${label} ${i + 1}/${n}: ${(r.ms / 1000).toFixed(2)}s  inv=${r.inventory} exec=${r.executed}${r.cached ? ` cached=${r.cached}` : ''} ${JSON.stringify(r.verdicts)}`);
  }
  return out;
}

/** Interleaves tzap (n runs) and Stryker (m runs) so background drift hits both alike. */
async function interleaved(nT, nS, runT, runS, label) {
  const T = [], S = [];
  for (let i = 0; i < Math.max(nT, nS); i++) {
    if (i < nT) {
      const r = await runT(i);
      T.push(r);
      log(`  ${label} tzap ${i + 1}/${nT}: ${(r.ms / 1000).toFixed(2)}s inv=${r.inventory} exec=${r.executed}${r.cached ? ` cached=${r.cached}` : ''} ${JSON.stringify(r.verdicts)}`);
    }
    if (i < nS) {
      const r = await runS(i);
      S.push(r);
      log(`  ${label} stryker ${i + 1}/${nS}: ${(r.ms / 1000).toFixed(2)}s inv=${r.inventory} exec=${r.executed}${r.cached ? ` reused=${r.cached}` : ''} ${JSON.stringify(r.verdicts)}`);
    }
  }
  return { T, S };
}

// ---------------------------------------------------------------------------------------------
// Main

log(`work dir ${WORK}`);
mkdirSync(WORK, { recursive: true });
const SNAP = await snapshotTzap();
TZAP = SNAP.bin;
log(`tzap build snapshot ${SNAP.hash} (${SNAP.attempts} attempt(s))`);
results.machine = machine();
results.machine.tzapBuild = SNAP.hash;
results.machine.loadBeforeSetup = await cpuBusy();
const main = setupVariant('main');
const stat = ONLY.includes('S9') ? setupVariant('static') : undefined;
results.config = {
  runs: RUNS,
  strykerRuns: STRYKER_RUNS,
  vitest: main.vitestVersion,
  stryker: main.strykerVersion,
  tzapFlags: '--no-arid (tzap filters Stryker lacks switched off, for equal inventory)',
  strykerConfig: JSON.parse(readFileSync(path.join(HERE, 'config', 'stryker.config.json'), 'utf8')),
  installMs: { main: main.installMs, static: stat?.installMs },
  workDir: WORK,
};
const D = main.dir;
const rep = (name) => path.join(WORK, 'reports', name);
const cacheDir = (name) => path.join(WORK, 'cache', name);
save();

// Sanity: the suite is green on both variants with the pinned Vitest.
for (const v of [main, stat].filter(Boolean)) {
  const r = await exec(process.execPath, [path.join(v.dir, 'node_modules', 'vitest', 'vitest.mjs'), 'run'], v.dir);
  if (r.code !== 0) throw new Error(`the fixture suite is red in ${v.dir}:\n${r.lines.slice(-20).map((l) => l.s).join('\n')}`);
}

// --- S1: full run -------------------------------------------------------------------------------
let strykerConcurrency = opt('stryker-concurrency') ? Number(opt('stryker-concurrency')) : undefined;
let s1t;
if (ONLY.includes('S1')) {
  log('S1: full run, Vitest, cold');
  const load = await cpuBusy();
  const S1 = (results.scenarios.S1 = { title: 'Full run, one Vitest package, cold', load, series: [] });

  if (WITH_STRYKER && strykerConcurrency === undefined) {
    // Stryker's concurrency is chosen by measurement (one run each), so tzap is compared with the
    // fastest Stryker this machine can give. These probe runs are reported, not hidden.
    const probe = [];
    for (const c of STRYKER_CANDIDATES) {
      const r = await stryker(D, ['--concurrency', String(c)]);
      log(`  stryker concurrency probe c=${c}: ${(r.ms / 1000).toFixed(2)}s`);
      probe.push({ concurrency: c, ms: r.ms });
    }
    strykerConcurrency = probe.reduce((a, b) => (b.ms < a.ms ? b : a)).concurrency;
    S1.strykerProbe = probe;
  }
  results.config.strykerConcurrency = strykerConcurrency;
  results.config.strykerConcurrencySource = S1.strykerProbe ? `fastest of ${STRYKER_CANDIDATES.join(', ')}, one probe run each, see S1` : 'set with --stryker-concurrency';
  const sc = ['--concurrency', String(strykerConcurrency ?? 4)];

  const { T, S } = await interleaved(RUNS, WITH_STRYKER ? STRYKER_RUNS : 0, () => tzap(D, [], { reportDir: rep('s1') }), () => stryker(D, sc), 'S1');
  s1t = T;
  S1.series.push(series('tzap warm (default workers)', 'tzap', T));
  if (S.length) {
    S1.series.push(series(`StrykerJS perTest, concurrency ${strykerConcurrency}`, 'stryker', S));
    S1.parity = parity(T.at(-1).mutants, S.at(-1).mutants);
  }
  save();

  if (WITH_REFERENCE) {
    // The reference engine: one fresh process per mutant. Slow; one run, labelled n=1. Its
    // concurrency matches Stryker's so the two per-mutant-process designs are compared like for like.
    const r = await tzap(D, ['--engine', 'reference', '--concurrency', String(strykerConcurrency ?? 4)], { reportDir: rep('s1-ref') });
    log(`  S1 tzap reference: ${(r.ms / 1000).toFixed(2)}s ${JSON.stringify(r.verdicts)}`);
    S1.series.push(series(`tzap reference engine, concurrency ${strykerConcurrency ?? 4}`, 'tzap-reference', [r]));
    S1.selfDifferential = parity(T.at(-1).mutants, r.mutants);
    save();
  }

  if (WITH_SCALING) {
    S1.scaling = [];
    for (const w of SCALING) {
      const runs = await timed(`S1 tzap --workers ${w}`, RUNS, () => tzap(D, ['--workers', String(w)], { reportDir: rep(`s1-w${w}`) }));
      S1.scaling.push(series(`tzap warm --workers ${w}`, 'tzap', runs, { workers: w }));
      save();
    }
  }
}

// --- S3 / S4: diff run --------------------------------------------------------------------------
if (ONLY.includes('S3') || ONLY.includes('S4')) {
  const inv = inventory(D);
  const patch = makePatch(D, inv);
  const patchFile = path.join(WORK, 'bench.patch');
  writeFileSync(patchFile, patch.diff);
  writeFileSync(path.join(HERE, 'results', 'S3.patch'), patch.diff);
  const scoped = inventory(D, ['--patch', patchFile]);
  const guard = { changedLines: patch.changedLines, files: patch.files, strykerMutate: patch.ranges, mutantsInScope: scoped.length, inventory: inv.length };
  if (scoped.length === 0) {
    // jzap's first diff benchmark reported 158x for a patch that hit no mutants.
    results.scenarios.S3 = { title: 'Diff run, synthetic 10-line PR, cold', refused: 'the synthetic patch hits no mutants; no figure is recorded', guard };
    log('S3: REFUSED — the patch hits no mutants');
  } else {
    if (ONLY.includes('S3')) {
      log(`S3: diff run, ${patch.changedLines} changed lines, ${scoped.length} mutants in scope`);
      const load = await cpuBusy();
      const { T, S } = await interleaved(
        RUNS,
        WITH_STRYKER ? STRYKER_RUNS : 0,
        () => tzap(D, ['--patch', patchFile], { reportDir: rep('s3') }),
        () => stryker(D, ['--concurrency', String(strykerConcurrency ?? 4), '--mutate', patch.ranges.join(',')]),
        'S3',
      );
      const S3 = (results.scenarios.S3 = { title: 'Diff run, synthetic 10-line PR, cold', load, guard, series: [series('tzap warm, --patch', 'tzap', T)] });
      if (T.some((r) => r.inventory === 0) || S.some((r) => r.inventory === 0)) S3.refused = 'a tool analysed zero mutants for the patch; the ratio would be meaningless';
      if (S.length) {
        S3.series.push(series(`StrykerJS --mutate ranges, concurrency ${strykerConcurrency}`, 'stryker', S));
        S3.parity = parity(T.at(-1).mutants, S.at(-1).mutants);
      }
      save();
    }
    if (ONLY.includes('S4')) {
      log('S4: same diff, warm cache');
      const cd = cacheDir('s4');
      rmSync(cd, { recursive: true, force: true });
      const prime = await tzap(D, ['--patch', patchFile, '--cache-dir', cd], { reportDir: rep('s4') });
      const load = await cpuBusy();
      const T = await timed('S4 tzap', RUNS, () => tzap(D, ['--patch', patchFile, '--cache-dir', cd], { reportDir: rep('s4') }));
      results.scenarios.S4 = {
        title: 'Diff run, same PR, warm cache',
        load,
        guard,
        prime: strip(prime),
        series: [series('tzap warm, --patch, --cache-dir (primed)', 'tzap', T)],
        notes: ['StrykerJS not run: its --incremental does not combine with a diff scope in a way that isolates this case (the task scoped Stryker to S1, S3, S5, S6).'],
      };
      save();
    }
  }
}

// --- S5: re-run, no changes, warm cache ----------------------------------------------------------
let s5prime;
if (ONLY.includes('S5') || ONLY.includes('S6')) {
  resetSources('main');
  rmSync(cacheDir('s5'), { recursive: true, force: true });
  s5prime = { tzap: await tzap(D, ['--cache-dir', cacheDir('s5')], { reportDir: rep('s5') }) };
  if (WITH_STRYKER) {
    rmSync(path.join(D, 'reports', 'stryker-incremental.json'), { force: true });
    s5prime.stryker = await stryker(D, ['--concurrency', String(strykerConcurrency ?? 4), '--incremental']);
  }
}
if (ONLY.includes('S5')) {
  log('S5: re-run with no changes, warm cache');
  const load = await cpuBusy();
  const { T, S } = await interleaved(
    RUNS,
    WITH_STRYKER ? STRYKER_RUNS : 0,
    () => tzap(D, ['--cache-dir', cacheDir('s5')], { reportDir: rep('s5') }),
    () => stryker(D, ['--concurrency', String(strykerConcurrency ?? 4), '--incremental']),
    'S5',
  );
  const S5 = (results.scenarios.S5 = { title: 'Re-run with no changes, warm cache', load, prime: { tzap: strip(s5prime.tzap), stryker: s5prime.stryker && strip(s5prime.stryker) }, series: [series('tzap warm, --cache-dir', 'tzap', T)] });
  if (S.length) S5.series.push(series(`StrykerJS --incremental, concurrency ${strykerConcurrency}`, 'stryker', S));
  save();
}

// --- S6: re-run after a one-line change, warm cache ----------------------------------------------
if (ONLY.includes('S6')) {
  // The edit changes a string literal inside code no test reaches, so no verdict should change:
  // what is measured is invalidation scope. Chosen from the primed report, deterministically.
  const target = s5prime.tzap.mutants
    .filter((m) => m.status === 'NoCoverage' && m.mutatorName === 'StringLiteral' && !m.static && m.location.start.line === m.location.end.line && m.original.length > 2)
    .sort((a, b) => a.file.localeCompare(b.file) || a.location.start.line - b.location.start.line)[0];
  if (!target) throw new Error('S6: no uncovered string literal to edit in the fixture');
  const file = path.join(D, target.file.replace(/^.*?\bsrc[\\/]/, 'src/'));
  const original = readFileSync(file, 'utf8');
  const lines = original.split('\n');
  const L = target.location.start.line - 1;
  const lit = target.original;
  const edited = lit.slice(0, -1) + ' (edited)' + lit.slice(-1);
  if (!lines[L].includes(lit)) throw new Error(`S6: literal ${lit} not on line ${L + 1} of ${file}`);
  lines[L] = lines[L].replace(lit, edited);
  const patched = lines.join('\n');
  const cacheFile = path.join(cacheDir('s5'), 'tzap-cache.txt');
  const strykerInc = path.join(D, 'reports', 'stryker-incremental.json');
  // Each repetition restores the pre-change cache: otherwise only the first run does the
  // invalidation work and the median measures a no-change run (jzap's first S6 did exactly that).
  const pristineCache = readFileSync(cacheFile, 'utf8');
  const pristineInc = WITH_STRYKER ? readFileSync(strykerInc, 'utf8') : undefined;
  log(`S6: one-line change at ${target.file}:${L + 1} (${lit} -> ${edited})`);
  const load = await cpuBusy();
  let T, S;
  try {
    writeFileSync(file, patched);
    ({ T, S } = await interleaved(
      RUNS,
      WITH_STRYKER ? STRYKER_RUNS : 0,
      () => {
        writeFileSync(cacheFile, pristineCache);
        return tzap(D, ['--cache-dir', cacheDir('s5')], { reportDir: rep('s6') });
      },
      () => {
        writeFileSync(strykerInc, pristineInc);
        return stryker(D, ['--concurrency', String(strykerConcurrency ?? 4), '--incremental']);
      },
      'S6',
    ));
  } finally {
    writeFileSync(file, original);
  }
  const S6 = (results.scenarios.S6 = {
    title: 'Re-run after a one-line change, warm cache',
    load,
    edit: { file: target.file, line: L + 1, from: lit, to: edited },
    series: [series('tzap warm, --cache-dir (pre-change cache restored each run)', 'tzap', T)],
  });
  if (T.some((r) => r.redTests > 0)) S6.warning = 'the edit turned a test red; the scenario no longer isolates invalidation';
  if (S.length) S6.series.push(series(`StrykerJS --incremental (pre-change file restored each run), concurrency ${strykerConcurrency}`, 'stryker', S));
  save();
}

// --- S9: static-heavy package --------------------------------------------------------------------
if (ONLY.includes('S9') && stat) {
  log('S9: static-heavy package, full run');
  const load = await cpuBusy();
  const { T, S } = await interleaved(
    RUNS,
    WITH_STRYKER ? STRYKER_RUNS : 0,
    () => tzap(stat.dir, [], { reportDir: rep('s9') }),
    () => stryker(stat.dir, ['--concurrency', String(strykerConcurrency ?? 4)]),
    'S9',
  );
  const S9 = (results.scenarios.S9 = { title: 'Package with many static mutants, full run', load, series: [series('tzap warm', 'tzap', T)] });
  if (S.length) {
    S9.series.push(series(`StrykerJS perTest, concurrency ${strykerConcurrency}`, 'stryker', S));
    S9.parity = parity(T.at(-1).mutants, S.at(-1).mutants);
  }
  save();
}

// Declared, not run: the scenarios that need later milestones.
results.scenarios.S2 = { title: 'Full run, one Jest package, cold', skipped: 'no Jest variant of the bench fixture yet (the Jest runner landed in a5e8147 while this harness was being built; the generator emits Vitest only)' };
results.scenarios.S7 = { title: 'Full run, monorepo with a test-less library', skipped: 'no monorepo bench fixture yet; tzap supports monorepos but the generator emits one package' };
results.scenarios.S8 = { title: 'Frontend package (TSX + jsdom), full run', skipped: 'needs jsdom/happy-dom environments (M20)' };
results.machine.loadAfter = await cpuBusy();
save();
log(`wrote ${path.relative(process.cwd(), OUT)}; render with node tools/bench/render.mjs`);
