#!/usr/bin/env node
/**
 * Renders the bench's raw results into tools/bench/report.md and the checked-in plain-text report
 * tools/bench/results/bench-report-<platform>.txt.
 *
 *   node tools/bench/render.mjs [results/raw-windows.json]
 *
 * Rules the renderer enforces rather than trusts:
 * - A time is always "median (min–max, n=N)". A single run is printed as "n=1, single run" and
 *   never enters a ratio.
 * - A ratio needs n >= 3 on both sides, a non-empty inventory on both sides, and a scenario that
 *   was not refused (S3's no-mutants-in-scope guard).
 * - Work parity (inventory per tool and the shared set) is printed next to every comparison.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const rawFile = path.resolve(process.argv[2] ?? path.join(HERE, 'results', `raw-${process.platform === 'win32' ? 'windows' : process.platform}.json`));
const R = JSON.parse(readFileSync(rawFile, 'utf8'));
const platform = path.basename(rawFile).replace(/^raw-|\.json$/g, '');

const median = (xs) => {
  const s = [...xs].sort((a, b) => a - b);
  const m = s.length >> 1;
  return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2;
};
const sec = (ms) => (ms / 1000).toFixed(2);
function time(series) {
  const t = series.runs.map((r) => r.ms);
  if (t.length === 1) return `${sec(t[0])}s (n=1, single run)`;
  return `${sec(median(t))}s (${sec(Math.min(...t))}–${sec(Math.max(...t))}, n=${t.length})`;
}
function ratio(a, b) {
  // b / a: how many times faster a is than b.
  if (!a || !b || a.runs.length < 3 || b.runs.length < 3) return undefined;
  if (a.runs.some((r) => r.inventory === 0) || b.runs.some((r) => r.inventory === 0)) return undefined;
  return median(b.runs.map((r) => r.ms)) / median(a.runs.map((r) => r.ms));
}
const last = (s) => s.runs.at(-1);
const verdicts = (v) =>
  ['Killed', 'Survived', 'NoCoverage', 'Timeout', 'RuntimeError', 'CompileError', 'Ignored']
    .filter((k) => v[k])
    .map((k) => `${{ Killed: 'K', Survived: 'S', NoCoverage: 'NC', Timeout: 'T', RuntimeError: 'RE', CompileError: 'CE', Ignored: 'I' }[k]} ${v[k]}`)
    .join(' / ');
const perMutant = (r) => (r.testExecutions === undefined || !r.executed ? 'n/a' : (r.testExecutions / r.executed).toFixed(2));
const loadNote = (l) => (l === undefined ? '' : `${l}%`);

function table(head, rows) {
  const md = [`| ${head.join(' | ')} |`, `|${head.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.join(' | ')} |`)].join('\n');
  const plain = (c) => String(c).replace(/\*\*|`/g, '');
  const w = head.map((h, i) => Math.max(h.length, ...rows.map((r) => plain(r[i]).length)));
  const line = (r) => r.map((c, i) => plain(c).padEnd(w[i])).join('  ').trimEnd();
  const txt = [line(head), w.map((x) => '-'.repeat(x)).join('  '), ...rows.map(line)].join('\n');
  return { md, txt };
}

const md = [];
const txt = [];
const both = (...lines) => {
  for (const s of lines) {
    md.push(s);
    txt.push(s.replace(/\*\*/g, '').replace(/`/g, ''));
  }
};
const heading = (s, level = 2) => {
  md.push(`${'#'.repeat(level)} ${s}`, '');
  txt.push('', s, (level === 2 ? '=' : '-').repeat(s.length), '');
};
const tbl = (t) => {
  md.push(t.md, '');
  txt.push(t.txt, '');
};

const M = R.machine;
md.push(`# tzap benchmark report (${platform})`, '', `Generated by \`node tools/bench/render.mjs\` from \`${path.relative(HERE, rawFile).replace(/\\/g, '/')}\`; do not edit by hand.`, '');
txt.push(`tzap benchmark report (${platform})`, '='.repeat(30), '', `Generated by tools/bench/render.mjs from ${path.basename(rawFile)}.`, '');
both(`- Machine: ${M.cpu}, ${M.logicalCpus} logical CPUs, ${M.memoryGB} GB, ${M.platform}`);
both(`- Node ${M.node}; tzap ${M.tzapVersion} at ${M.tzapCommit}, build snapshot ${M.tzapBuild ?? 'none (live workspace dist)'}; Vitest ${R.config.vitest}; StrykerJS ${R.config.stryker} + @stryker-mutator/vitest-runner`);
both(`- Date: ${M.date}`);
both(`- Runs: tzap ${R.config.runs}, StrykerJS ${R.config.strykerRuns}; tzap and Stryker runs interleaved; median with min–max, never a best run`);
both(`- Stryker concurrency: ${R.config.strykerConcurrency} (${R.config.strykerConcurrencySource ?? 'chosen by measurement, see S1'}); tzap: ${R.config.tzapFlags}`);
both(`- Background CPU load (2 s sample, whole machine): ${M.loadBeforeSetup}% before setup, ${M.loadAfter ?? '?'}% after; per scenario below`);
both(`- Install time excluded from every timing (npm install of the work copy: ${R.config.installMs?.main ? `${sec(R.config.installMs.main)}s` : 'reused from a previous run'})`);
both('');
both(
  '**Caveat.** A developer machine, not an isolated bench host: no fixed governor, turbo on, other applications open. Treat ratios as indicative and absolute numbers as machine-specific; compare medians within one report only. Differences below ~10% are unmeasured (jzap measured that ordering effect under load). Windows figures only: process spawn is ~35 ms here, 2–3x cheaper on Linux, which moves Stryker more than tzap.',
);
both('');

// --- headline ----------------------------------------------------------------------------------
heading('Results');
const order = ['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'S9'];
const rows = [];
for (const id of order) {
  const s = R.scenarios[id];
  if (!s) continue;
  if (s.skipped) {
    rows.push([id, s.title, 'skipped', '', '', '', s.skipped]);
    continue;
  }
  if (!s.series) {
    rows.push([id, s.title, 'REFUSED', '', '', '', s.refused]);
    continue;
  }
  const t = s.series.find((x) => x.tool === 'tzap');
  const st = s.series.find((x) => x.tool === 'stryker');
  const r = s.refused ? undefined : ratio(t, st);
  const inv = st ? `${last(t).inventory} / ${last(st).inventory}${s.parity ? ` (shared ${s.parity.shared})` : ''}` : `${last(t).inventory}`;
  const exec = st ? `${last(t).executed} / ${last(st).executed}` : `${last(t).executed}${last(t).cached ? ` (${last(t).cached} cached)` : ''}`;
  rows.push([id, s.title, time(t), st ? time(st) : '—', r ? `**${r.toFixed(2)}x**` : st ? 'n/a' : '—', inv, exec]);
}
tbl(table(['#', 'Scenario', 'tzap', 'StrykerJS', 'Stryker / tzap', 'Mutants tzap / Stryker', 'Executed tzap / Stryker'], rows));
both('"Executed" counts mutants that ran at least one test in that run (cached or reused results excluded). Stryker / tzap is the ratio of medians; it is printed only with n >= 3 on both sides and non-empty inventories.');
both('');

// --- kill criteria -----------------------------------------------------------------------------
heading('Kill criteria (docs/delivery-plan.md)');
const kc = [];
for (const [id, need] of [['S1', 3], ['S3', 10]]) {
  const s = R.scenarios[id];
  const t = s?.series?.find((x) => x.tool === 'tzap');
  const st = s?.series?.find((x) => x.tool === 'stryker');
  const r = s && !s.refused ? ratio(t, st) : undefined;
  const p = s?.parity;
  const par = p ? `inventory ${last(t).inventory} vs ${last(st).inventory}, shared ${p.shared}, tzap-only ${p.aOnly}, Stryker-only ${p.bOnly}` : 'no parity data';
  kc.push([id, `>= ${need}x`, r ? `${r.toFixed(2)}x` : 'not measured', r === undefined ? 'UNKNOWN' : r >= need ? 'MET' : 'NOT MET', par]);
}
tbl(table(['Scenario', 'Required', 'Measured', 'Verdict', 'Work parity'], kc));
both('S2 (>= 5x on Jest) is not checked: no Jest bench fixture yet.');
both('');

// --- per scenario ------------------------------------------------------------------------------
heading('Per scenario');
const phaseRow = (s) => {
  const keys = [...new Set(s.runs.flatMap((r) => Object.keys(r.phases ?? {})))].filter((k) => s.runs.every((r) => r.phases?.[k] !== undefined));
  const parts = keys.map((k) => `${k} ${sec(median(s.runs.map((r) => r.phases[k])))}s`);
  if (s.tool !== 'stryker') {
    const other = median(s.runs.map((r) => r.ms - keys.reduce((a, k) => a + r.phases[k], 0)));
    parts.push(`outside phases ${sec(other)}s`);
  }
  return parts.join(', ') || '—';
};
for (const id of order) {
  const s = R.scenarios[id];
  if (!s || s.skipped) continue;
  heading(`${id} · ${s.title}`, 3);
  if (s.refused) both(`**Refused:** ${s.refused}`, '');
  if (s.load !== undefined) both(`Background CPU load before the scenario: ${loadNote(s.load)}.`);
  if (s.guard) both(`Patch: ${s.guard.changedLines} changed lines in ${s.guard.files.join(', ')}; ${s.guard.mutantsInScope} of ${s.guard.inventory} mutants in tzap's scope. Stryker given \`--mutate ${s.guard.strykerMutate.join(',')}\`. The patch is checked in as \`results/S3.patch\`.`);
  if (s.edit) both(`Edit: \`${s.edit.file}:${s.edit.line}\` ${s.edit.from} → ${s.edit.to} (inside code no test reaches, so no verdict should change).`);
  if (s.warning) both(`**Warning:** ${s.warning}`);
  both('');
  if (!s.series) continue;
  const rs = s.series.map((x) => {
    const r = last(x);
    return [x.label, time(x), r.inventory, r.executed, r.cached || 0, r.static, verdicts(r.verdicts), perMutant(r), phaseRow(x)];
  });
  tbl(table(['Run', 'Wall clock', 'Mutants', 'Executed', 'Cached/reused', 'Static', 'Verdicts', 'Tests per executed mutant', 'Phases (median)'], rs));
  if (s.parity) {
    const p = s.parity;
    both(`Work parity (tzap vs Stryker, key = file, mutator, start–end, normalised replacement): shared ${p.shared}, tzap-only ${p.aOnly}, Stryker-only ${p.bOnly}. Verdict disagreements on shared mutants: ${Object.keys(p.disagree).length ? Object.entries(p.disagree).map(([k, v]) => `${k} ${v}`).join(', ') : 'none'} (tzap/Stryker).`);
    if (p.aOnly) both(`tzap-only sample: ${p.aOnlySample.map((x) => `\`${x}\``).join('; ')}`);
    if (p.bOnly) both(`Stryker-only sample: ${p.bOnlySample.map((x) => `\`${x}\``).join('; ')}`);
    both('');
  }
  if (s.selfDifferential) {
    const p = s.selfDifferential;
    both(`Self-differential (warm vs reference, same inventory ${p.shared}): ${Object.keys(p.disagree).length ? `**${Object.values(p.disagree).reduce((a, b) => a + b, 0)} verdict differences**: ${Object.entries(p.disagree).map(([k, v]) => `${k} ${v}`).join(', ')} (warm/reference)` : 'identical verdicts'}.`);
    both('');
  }
  if (s.strykerProbe) {
    both(`Stryker concurrency probe (one run each, used only to pick the fastest setting): ${s.strykerProbe.map((p) => `c=${p.concurrency} ${sec(p.ms)}s`).join(', ')}.`);
    both('');
  }
  if (s.scaling) {
    const base = median(s.scaling[0].runs.map((r) => r.ms));
    tbl(table(['tzap workers', 'Wall clock', 'Speed-up vs 1 worker', 'Phases (median)'], s.scaling.map((x) => [x.workers, time(x), `${(base / median(x.runs.map((r) => r.ms))).toFixed(2)}x`, phaseRow(x)])));
  }
  if (s.prime) {
    const p = s.prime.tzap ?? s.prime;
    both(`Cache primed by one tzap run before the timed runs (not in the median): ${sec(p.ms)}s.${s.prime.stryker ? ` Stryker's incremental file primed the same way: ${sec(s.prime.stryker.ms)}s.` : ''}`);
    both('');
  }
  for (const n of s.notes ?? []) both(`Note: ${n}`, '');
}

// --- not yet measured --------------------------------------------------------------------------
heading('Declared but not yet measured');
both('- Peak RSS, CPU-seconds, process and thread counts, worker boots: need a process-tree sampler (Windows has no rusage for grandchildren); tzap does not report worker boots yet.');
both('- tzap phase timings come from its JSON report (`timings`); discovery and report writing are outside every phase and show up as "outside phases". Stryker phases are taken from its log lines, timestamped on arrival: start to "Instrumented", dry run, and the rest (mutation testing + reporting).');
both('- CI gates on machine-independent metrics (`budgets.yaml`) are not wired yet.');
both('');

writeFileSync(path.join(HERE, 'report.md'), `${md.join('\n').replace(/\n{3,}/g, '\n\n')}\n`);
writeFileSync(path.join(HERE, 'results', `bench-report-${platform}.txt`), `${txt.join('\n').replace(/\n{3,}/g, '\n\n')}\n`);
console.log(`wrote tools/bench/report.md and tools/bench/results/bench-report-${platform}.txt`);
